#!/usr/bin/env python3
"""Create, validate, index, and traverse Copernicus planning workpacks."""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import date
from graphlib import CycleError, TopologicalSorter
import json
import os
from pathlib import Path, PurePosixPath
import re
import sys
import tempfile


GENERATED = "<!-- generated by Copernicus Planning; edit concept files instead -->"
STATUSES = {"draft", "ready", "active", "blocked", "done", "deferred"}
PRIORITIES = {"vital": 0, "important": 1, "later": 2}
DESIGN_SECTIONS = (
    "Outcome",
    "Current evidence",
    "Design",
    "Interfaces and boundaries",
    "Decisions and alternatives",
    "Risks and recovery",
    "Non-goals",
)
WORKPACK_SECTIONS = (
    "Outcome",
    "Evidence and assumptions",
    "Scope",
    "Tests written first",
    "Implementation",
    "Acceptance",
    "Risks and stop conditions",
    "Handoff",
)
PLACEHOLDER = re.compile(r"(?i)(\[replace[^]]*\]|\bTODO\b|\bTBD\b)")


class PlanningError(ValueError):
    pass


def scalar(raw: str, path: Path, line: int):
    raw = raw.strip()
    if not raw:
        return ""
    if raw[0] in '"[{' or raw in {"true", "false", "null"} or re.fullmatch(
        r"-?(?:0|[1-9]\d*)(?:\.\d+)?", raw
    ):
        try:
            return json.loads(raw)
        except json.JSONDecodeError as exc:
            raise PlanningError(f"{path}:{line}: invalid JSON-compatible YAML value") from exc
    return raw


def read_concept(path: Path) -> tuple[dict, str]:
    if path.is_symlink():
        raise PlanningError(f"symlinked concept is not allowed: {path}")
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise PlanningError(f"missing YAML frontmatter: {path}")
    try:
        end = next(i for i, line in enumerate(lines[1:], 1) if line.strip() == "---")
    except StopIteration as exc:
        raise PlanningError(f"unterminated YAML frontmatter: {path}") from exc

    meta = {}
    for number, line in enumerate(lines[1:end], 2):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[:1].isspace() or ":" not in line:
            raise PlanningError(
                f"{path}:{number}: use flat key: value frontmatter; nested YAML is unsupported"
            )
        key, raw = line.split(":", 1)
        key = key.strip()
        if not re.fullmatch(r"[a-z][a-z0-9_]*", key):
            raise PlanningError(f"{path}:{number}: invalid frontmatter key {key!r}")
        if key in meta:
            raise PlanningError(f"{path}:{number}: duplicate frontmatter key {key!r}")
        meta[key] = scalar(raw, path, number)
    return meta, "\n".join(lines[end + 1 :]).strip() + "\n"


def require(meta: dict, fields: tuple[str, ...], path: Path) -> None:
    missing = [field for field in fields if field not in meta]
    if missing:
        raise PlanningError(f"{path}: missing frontmatter fields: {', '.join(missing)}")


def sections(body: str) -> dict[str, str]:
    matches = list(re.finditer(r"(?m)^## ([^\n]+?)\s*$", body))
    found = {}
    for index, match in enumerate(matches):
        name = match.group(1)
        if name in found:
            raise PlanningError(f"duplicate section: {name}")
        end = matches[index + 1].start() if index + 1 < len(matches) else len(body)
        found[name] = body[match.end() : end].strip()
    return found


def check_sections(path: Path, body: str, required: tuple[str, ...], complete: bool) -> None:
    found = sections(body)
    missing = [name for name in required if name not in found]
    if missing:
        raise PlanningError(f"{path}: missing sections: {', '.join(missing)}")
    if complete:
        incomplete = [name for name in required if not found[name] or PLACEHOLDER.search(found[name])]
        if incomplete:
            raise PlanningError(f"{path}: incomplete sections: {', '.join(incomplete)}")


def relative_path(value: object, field: str, path: Path) -> str:
    if not isinstance(value, str) or not value:
        raise PlanningError(f"{path}: {field} entries must be non-empty strings")
    if "\\" in value or "\x00" in value:
        raise PlanningError(f"{path}: unsafe {field} path {value!r}")
    candidate = PurePosixPath(value)
    if candidate.is_absolute() or any(part in {"", ".", ".."} for part in candidate.parts):
        raise PlanningError(f"{path}: unsafe {field} path {value!r}")
    if ":" in candidate.parts[0]:
        raise PlanningError(f"{path}: unsafe {field} path {value!r}")
    return value


def string_list(meta: dict, field: str, path: Path) -> list[str]:
    value = meta[field]
    if not isinstance(value, list) or any(not isinstance(item, str) for item in value):
        raise PlanningError(f"{path}: {field} must be an inline JSON string array")
    if len(value) != len(set(value)):
        raise PlanningError(f"{path}: {field} contains duplicates")
    return value


def validate_design(path: Path, implementation_ready: bool) -> dict:
    meta, body = read_concept(path)
    require(meta, ("type", "title", "description", "status", "mode", "updated", "authority"), path)
    if meta["type"] != "design":
        raise PlanningError(f"{path}: type must be design")
    if meta["status"] not in {"draft", "ready", "done"}:
        raise PlanningError(f"{path}: invalid design status {meta['status']!r}")
    if meta["mode"] not in {"workpacks", "discovery"}:
        raise PlanningError(f"{path}: design mode must be workpacks or discovery")
    for field in ("title", "description", "updated", "authority"):
        if not isinstance(meta[field], str) or not meta[field].strip():
            raise PlanningError(f"{path}: {field} must be a non-empty string")
    try:
        date.fromisoformat(meta["updated"])
    except ValueError as exc:
        raise PlanningError(f"{path}: updated must be an ISO date") from exc
    complete = meta["status"] in {"ready", "done"}
    check_sections(path, body, DESIGN_SECTIONS, complete)
    if implementation_ready and meta["status"] not in {"ready", "done"}:
        raise PlanningError(f"{path}: implementation-ready bundle needs a ready design")
    return meta


def validate_workpack(path: Path) -> dict:
    meta, body = read_concept(path)
    require(
        meta,
        (
            "type",
            "id",
            "title",
            "description",
            "status",
            "priority",
            "parent",
            "depends_on",
            "paths",
            "test_paths",
            "test_first",
            "test_waiver",
            "updated",
        ),
        path,
    )
    if meta["type"] != "workpack":
        raise PlanningError(f"{path}: type must be workpack")
    if not isinstance(meta["id"], str) or not re.fullmatch(r"WP-\d{3,}", meta["id"]):
        raise PlanningError(f"{path}: id must match WP-NNN")
    if path.stem != meta["id"]:
        raise PlanningError(f"{path}: filename must match workpack id {meta['id']}")
    if meta["status"] not in STATUSES:
        raise PlanningError(f"{path}: invalid status {meta['status']!r}")
    if meta["priority"] not in PRIORITIES:
        raise PlanningError(f"{path}: priority must be vital, important, or later")
    for field in ("title", "description", "updated"):
        if not isinstance(meta[field], str) or not meta[field].strip():
            raise PlanningError(f"{path}: {field} must be a non-empty string")
    try:
        date.fromisoformat(meta["updated"])
    except ValueError as exc:
        raise PlanningError(f"{path}: updated must be an ISO date") from exc
    if not isinstance(meta["parent"], str):
        raise PlanningError(f"{path}: parent must be a string")
    if not isinstance(meta["test_first"], bool):
        raise PlanningError(f"{path}: test_first must be true or false")
    if not isinstance(meta["test_waiver"], str):
        raise PlanningError(f"{path}: test_waiver must be a string")
    meta["depends_on"] = string_list(meta, "depends_on", path)
    meta["paths"] = [relative_path(item, "paths", path) for item in string_list(meta, "paths", path)]
    meta["test_paths"] = [
        relative_path(item, "test_paths", path) for item in string_list(meta, "test_paths", path)
    ]
    complete = meta["status"] in {"ready", "active", "blocked", "done"}
    check_sections(path, body, WORKPACK_SECTIONS, complete)
    if complete and not meta["paths"]:
        raise PlanningError(f"{path}: non-draft workpack must own at least one path")
    if complete and meta["test_first"] and not meta["test_paths"]:
        raise PlanningError(f"{path}: test-first workpack must list test_paths")
    if meta["test_first"] and meta["test_waiver"].strip():
        raise PlanningError(f"{path}: test-first workpack cannot also declare a test_waiver")
    if complete and not meta["test_first"] and not meta["test_waiver"].strip():
        raise PlanningError(f"{path}: test_first false requires a specific test_waiver")
    return meta


def graph_waves(graph: dict[str, set[str]], label: str) -> list[list[str]]:
    sorter = TopologicalSorter(graph)
    try:
        sorter.prepare()
    except CycleError as exc:
        cycle = " -> ".join(exc.args[1]) if len(exc.args) > 1 else "unknown"
        raise PlanningError(f"{label} cycle: {cycle}") from exc
    waves = []
    while sorter.is_active():
        wave = sorted(sorter.get_ready())
        waves.append(wave)
        sorter.done(*wave)
    return waves


def reaches(graph: dict[str, set[str]], start: str, target: str) -> bool:
    pending = list(graph[start])
    seen = set()
    while pending:
        node = pending.pop()
        if node == target:
            return True
        if node not in seen:
            seen.add(node)
            pending.extend(graph[node])
    return False


def load_bundle(
    bundle: Path, implementation_ready: bool = False, repo_root: Path | None = None
) -> tuple[dict, dict[str, dict], list[list[str]]]:
    if not bundle.is_dir() or bundle.is_symlink():
        raise PlanningError(f"bundle must be a real directory: {bundle}")
    design = validate_design(bundle / "design.md", implementation_ready)
    workpack_dir = bundle / "workpacks"
    if not workpack_dir.is_dir() or workpack_dir.is_symlink():
        raise PlanningError(f"missing workpacks directory: {workpack_dir}")
    paths = [path for path in sorted(workpack_dir.glob("*.md")) if path.name != "index.md"]
    if not paths:
        raise PlanningError(f"no workpack concepts found in {workpack_dir}")

    workpacks = {}
    locations = {}
    for path in paths:
        meta = validate_workpack(path)
        identifier = meta["id"]
        if identifier in workpacks:
            raise PlanningError(f"duplicate workpack id {identifier}: {locations[identifier]} and {path}")
        workpacks[identifier] = meta
        locations[identifier] = path

    identifiers = set(workpacks)
    dependency_graph = {}
    parent_graph = {}
    for identifier, meta in workpacks.items():
        unknown = set(meta["depends_on"]) - identifiers
        if unknown:
            raise PlanningError(f"{locations[identifier]}: unknown dependencies: {', '.join(sorted(unknown))}")
        if identifier in meta["depends_on"]:
            raise PlanningError(f"{locations[identifier]}: workpack cannot depend on itself")
        parent = meta["parent"]
        if parent and parent not in identifiers:
            raise PlanningError(f"{locations[identifier]}: unknown parent {parent}")
        if parent == identifier:
            raise PlanningError(f"{locations[identifier]}: workpack cannot parent itself")
        dependency_graph[identifier] = set(meta["depends_on"])
        parent_graph[identifier] = {parent} if parent else set()

    waves = graph_waves(dependency_graph, "dependency")
    graph_waves(parent_graph, "parent")

    for left_index, left in enumerate(sorted(workpacks)):
        for right in sorted(workpacks)[left_index + 1 :]:
            shared = set(workpacks[left]["paths"]) & set(workpacks[right]["paths"])
            if shared and not reaches(dependency_graph, left, right) and not reaches(
                dependency_graph, right, left
            ):
                raise PlanningError(
                    f"independent workpacks {left} and {right} share paths without a dependency: "
                    + ", ".join(sorted(shared))
                )

    active_statuses = {"ready", "active", "blocked", "done"}
    if implementation_ready:
        unfinished = [
            identifier
            for identifier, meta in workpacks.items()
            if meta["status"] in {"draft", "blocked"}
        ]
        if unfinished:
            raise PlanningError(
                "implementation-ready bundle has draft or blocked workpacks: "
                + ", ".join(sorted(unfinished))
            )
        if any(meta["status"] in active_statuses and meta["test_first"] for meta in workpacks.values()):
            if repo_root is None:
                raise PlanningError("--implementation-ready needs --repo-root to verify test_paths")

    if repo_root is not None:
        root = repo_root.resolve()
        if not root.is_dir():
            raise PlanningError(f"repo root must be a directory: {repo_root}")
        for identifier, meta in workpacks.items():
            if meta["status"] not in active_statuses or not meta["test_first"]:
                continue
            for raw in meta["test_paths"]:
                target = (root / raw).resolve()
                if not target.is_relative_to(root) or not target.is_file():
                    raise PlanningError(f"{locations[identifier]}: missing confined test file {raw}")

    return design, workpacks, waves


def quote(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_new(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def write_generated(path: Path, text: str) -> None:
    if path.exists() and GENERATED not in path.read_text(encoding="utf-8"):
        raise PlanningError(f"refusing to overwrite non-generated index: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as handle:
        handle.write(text)
        temporary = Path(handle.name)
    os.replace(temporary, path)


def design_template(title: str, mode: str, today: str) -> str:
    return f'''---
type: design
title: {quote(title)}
description: "[replace with the observable design outcome]"
status: draft
mode: {mode}
updated: {quote(today)}
authority: "[replace with source-of-truth and freshness boundary]"
---

# {title}

## Outcome

[replace with user-visible behavior and observable success]

## Current evidence

[replace with observed facts, citations, and UNVERIFIED gaps]

## Design

[replace with the smallest coherent solution]

## Interfaces and boundaries

[replace with exact paths, interfaces, ownership, and authority limits]

## Decisions and alternatives

[replace with chosen option, rejected alternatives, and reversal trigger]

## Risks and recovery

[replace with failure modes, prevention, rollback, and stop conditions]

## Non-goals

[replace with deliberately excluded work]
'''


def workpack_template(today: str) -> str:
    return f'''---
type: workpack
id: WP-001
title: "[replace with one independently verifiable deliverable]"
description: "[replace with the workpack outcome]"
status: draft
priority: vital
parent: ""
depends_on: []
paths: []
test_paths: []
test_first: true
test_waiver: ""
updated: {quote(today)}
---

# WP-001 — [replace title]

## Outcome

[replace with observable result]

## Evidence and assumptions

[replace with source evidence, freshness, assumptions, and UNVERIFIED gaps]

## Scope

[replace with owned paths/interfaces and explicit non-goals]

## Tests written first

[replace with test cases, exact test paths, command, and expected red result]

## Implementation

[replace with ordered minimal edits, named symbols, and reuse points]

## Acceptance

[replace with exact commands, expected outputs, and requirement-to-test mapping]

## Risks and stop conditions

[replace with falsifier, rollback, blockers, and new-authority boundary]

## Handoff

[replace with prerequisites, completion evidence, and next consumer]
'''


def cmd_init(args: argparse.Namespace) -> None:
    bundle = Path(args.bundle)
    if "\n" in args.title or not args.title.strip():
        raise PlanningError("title must be one non-empty line")
    if args.mode not in {"workpacks", "discovery"}:
        raise PlanningError("init mode must be workpacks or discovery")
    bundle.mkdir(parents=True, exist_ok=False)
    (bundle / "workpacks").mkdir()
    today = date.today().isoformat()
    write_new(bundle / "design.md", design_template(args.title.strip(), args.mode, today))
    write_new(bundle / "workpacks/WP-001.md", workpack_template(today))
    write_new(
        bundle / "log.md",
        f"# Planning log\n\n## {today}\n\n- Initialized `{args.mode}` bundle.\n",
    )
    cmd_index(argparse.Namespace(bundle=str(bundle), write=True))
    print(bundle.resolve())


def root_index(design: dict, workpacks: dict[str, dict]) -> str:
    counts = Counter(meta["status"] for meta in workpacks.values())
    summary = ", ".join(f"{status}: {counts[status]}" for status in sorted(counts))
    return f"""{GENERATED}
# {design['title']}

{design['description']}

- [Design](design.md)
- [Workpacks](workpacks/index.md)
- [Planning log](log.md)

## Status

- Design: `{design['status']}`
- Workpacks: {summary}
"""


def workpack_index(workpacks: dict[str, dict], waves: list[list[str]]) -> str:
    lines = [GENERATED, "# Workpacks", "", "Dependency waves are derived from `depends_on`.", ""]
    for number, wave in enumerate(waves, 1):
        lines.extend([f"## Wave {number}", ""])
        for identifier in sorted(
            wave, key=lambda item: (PRIORITIES[workpacks[item]["priority"]], item)
        ):
            meta = workpacks[identifier]
            lines.append(
                f"- [{identifier}: {meta['title']}]({identifier}.md) — "
                f"`{meta['status']}` / `{meta['priority']}` — {meta['description']}"
            )
        lines.append("")
    return "\n".join(lines)


def cmd_validate(args: argparse.Namespace) -> None:
    load_bundle(
        Path(args.bundle),
        implementation_ready=args.implementation_ready,
        repo_root=Path(args.repo_root) if args.repo_root else None,
    )
    print("OK")


def cmd_index(args: argparse.Namespace) -> None:
    if not args.write:
        raise PlanningError("index is non-mutating unless --write is explicit")
    bundle = Path(args.bundle)
    design, workpacks, waves = load_bundle(bundle)
    write_generated(bundle / "index.md", root_index(design, workpacks))
    write_generated(bundle / "workpacks/index.md", workpack_index(workpacks, waves))
    print("OK")


def cmd_next(args: argparse.Namespace) -> None:
    _, workpacks, _ = load_bundle(Path(args.bundle))
    ready = [
        identifier
        for identifier, meta in workpacks.items()
        if meta["status"] == "ready"
        and all(workpacks[dependency]["status"] == "done" for dependency in meta["depends_on"])
    ]
    ready.sort(key=lambda item: (PRIORITIES[workpacks[item]["priority"]], item))
    print("\n".join(ready) if ready else "none")


def parser() -> argparse.ArgumentParser:
    command = argparse.ArgumentParser(description=__doc__)
    sub = command.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="create a new workpack bundle without overwriting")
    init.add_argument("bundle")
    init.add_argument("--title", required=True)
    init.add_argument("--mode", choices=("workpacks", "discovery"), default="workpacks")
    init.set_defaults(func=cmd_init)

    validate = sub.add_parser("validate", help="validate structure, graph, paths, and readiness")
    validate.add_argument("bundle")
    validate.add_argument("--implementation-ready", action="store_true")
    validate.add_argument("--repo-root")
    validate.set_defaults(func=cmd_validate)

    index = sub.add_parser("index", help="regenerate reserved navigation files")
    index.add_argument("bundle")
    index.add_argument("--write", action="store_true")
    index.set_defaults(func=cmd_index)

    next_parser = sub.add_parser("next", help="print ready workpacks whose dependencies are done")
    next_parser.add_argument("bundle")
    next_parser.set_defaults(func=cmd_next)
    return command


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    try:
        args.func(args)
        return 0
    except (OSError, PlanningError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
